/**
 * VAPID — how a push service knows the request really came from us
 * (RFC 8292). Each request carries a short-lived ES256 JWT signed with
 * our private key, plus the matching public key so the service can
 * check it.
 *
 * Keys are raw P-256 material, base64url-encoded, which is the format
 * every VAPID tool and the browser's `applicationServerKey` expect:
 * the public key is the 65-byte uncompressed point (0x04 ‖ X ‖ Y) and
 * the private key is the 32-byte scalar `d`.
 */

export interface VapidKeys {
  /** base64url, 65-byte uncompressed P-256 point. */
  publicKey: string;
  /** base64url, 32-byte private scalar. */
  privateKey: string;
}

export function base64UrlEncode(bytes: Uint8Array): string {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

export function base64UrlDecode(value: string): Uint8Array {
  const padded = value.replace(/-/g, "+").replace(/_/g, "/");
  const binary = atob(padded.padEnd(Math.ceil(padded.length / 4) * 4, "="));
  return Uint8Array.from(binary, (c) => c.charCodeAt(0));
}

/** The audience is the push endpoint's ORIGIN, not the full URL —
 * a full-URL audience is rejected by several services. */
export function audienceFor(endpoint: string): string {
  return new URL(endpoint).origin;
}

/**
 * WebCrypto will not import a bare P-256 scalar, so the private key is
 * rebuilt as a JWK from the scalar plus the X/Y taken from the public
 * key. Keeping the stored format raw (rather than JWK or PKCS#8) is
 * what lets the same key pair be generated by any standard VAPID tool.
 */
async function importSigningKey(keys: VapidKeys): Promise<CryptoKey> {
  const publicBytes = base64UrlDecode(keys.publicKey);
  if (publicBytes.length !== 65 || publicBytes[0] !== 0x04) {
    throw new Error("VAPID public key must be a 65-byte uncompressed P-256 point");
  }
  const jwk: JsonWebKey = {
    kty: "EC",
    crv: "P-256",
    x: base64UrlEncode(publicBytes.slice(1, 33)),
    y: base64UrlEncode(publicBytes.slice(33, 65)),
    d: keys.privateKey,
    ext: true,
    key_ops: ["sign"],
  };
  return crypto.subtle.importKey(
    "jwk",
    jwk,
    { name: "ECDSA", namedCurve: "P-256" },
    false,
    ["sign"],
  );
}

/** Services reject anything beyond 24h; 12h leaves room for clock skew
 * on both ends without ever approaching the limit. */
const TOKEN_TTL_SECONDS = 12 * 60 * 60;

export interface VapidHeaderOptions {
  endpoint: string;
  keys: VapidKeys;
  /** Contact address, so a push service can reach the sender. */
  subject: string;
  now?: number;
}

/**
 * The `Authorization` header value for a Web Push request:
 * `vapid t=<jwt>, k=<public key>`.
 */
export async function vapidAuthorization(
  options: VapidHeaderOptions,
): Promise<string> {
  const now = options.now ?? Date.now();
  const header = { typ: "JWT", alg: "ES256" };
  const claims = {
    aud: audienceFor(options.endpoint),
    exp: Math.floor(now / 1000) + TOKEN_TTL_SECONDS,
    sub: options.subject,
  };

  const encoder = new TextEncoder();
  const signingInput = `${base64UrlEncode(
    encoder.encode(JSON.stringify(header)),
  )}.${base64UrlEncode(encoder.encode(JSON.stringify(claims)))}`;

  const key = await importSigningKey(options.keys);
  // ECDSA over SHA-256 — WebCrypto emits the raw r‖s form JWS wants,
  // not the DER encoding OpenSSL would give.
  const signature = new Uint8Array(
    await crypto.subtle.sign(
      { name: "ECDSA", hash: "SHA-256" },
      key,
      encoder.encode(signingInput),
    ),
  );

  const jwt = `${signingInput}.${base64UrlEncode(signature)}`;
  return `vapid t=${jwt}, k=${options.keys.publicKey}`;
}
